// src/app/class-selector/class-selector.component.ts
// src/app/class-selector/class-selector.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

// Definieren der Typen für die Props
export interface Class {
  id: string;
  name: string;
  hitDie: string;
  subclasses: string[];
  spellcasting: boolean;
}

@Component({
  selector: 'app-class-selector',
  templateUrl: './class-selector.component.html',
  styleUrls: ['./class-selector.component.css']
})
export class ClassSelectorComponent {
  @Input() classes: Class[] = [];
  @Input() selected: string = '';
  
  @Output() onSelect = new EventEmitter<string>();

  handleClassSelection(event: Event) {
    const value = (event.target as HTMLSelectElement).value;
    this.onSelect.emit(value);
  }
}

<!-- src/app/class-selector/class-selector.component.html -->
<div>
    <h2>Select a Class</h2>
    <select [ngModel]="selected" (ngModelChange)="handleClassSelection($event)">
      <option value="">Select a Class</option>
      <option *ngFor="let cls of classes" [value]="cls.id">{{ cls.name }}</option>
    </select>
  </div>

// src/components/builder/ClassSelector.tsx
import React from 'react';

interface ClassSelectorProps {
  classes: { id: string; name: string; hitDie: string; subclasses: string[]; spellcasting: boolean }[];
  selected: string;
  onSelect: React.Dispatch<React.SetStateAction<string>>;
}

export default function ClassSelector({
  classes,
  selected,
  onSelect,
}: ClassSelectorProps) {
  return (
    <div>
      <h2>Select a Class</h2>
      <select value={selected} onChange={(e) => onSelect(e.target.value)}>
        <option value="">Select a Class</option>
        {classes.map((cls) => (
          <option key={cls.id} value={cls.id}>
            {cls.name}
          </option>
        ))}
      </select>
    </div>
  );
}
