// src/app/equipment-selector/equipment-selector.component.ts
// src/app/equipment-selector/equipment-selector.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

// Definieren der Typen für die Props
export interface EquipmentItem {
  id: string;
  name: string;
  category: string;
  cost: string;
}

@Component({
  selector: 'app-equipment-selector',
  templateUrl: './equipment-selector.component.html',
  styleUrls: ['./equipment-selector.component.css']
})
export class EquipmentSelectorComponent {
  @Input() options: EquipmentItem[] = [];
  @Input() selected: string[] = [];

  @Output() onToggle = new EventEmitter<string>();

  handleToggle(name: string) {
    this.onToggle.emit(name);
  }
}

<!-- src/app/equipment-selector/equipment-selector.component.html -->
<div>
    <h2>Select Equipment</h2>
    <div *ngFor="let item of options">
      <label>
        <input
          type="checkbox"
          [checked]="selected.includes(item.id)"
          (change)="handleToggle(item.id)"
        />
        {{ item.name }} ({{ item.cost }})
      </label>
    </div>
  </div>

// src/components/builder/EquipmentSelector.tsx
import React from 'react';

interface EquipmentItem {
  id: string;
  name: string;
  category: string;
  cost: string;
}

interface EquipmentSelectorProps {
  options: EquipmentItem[];
  selected: string[];
  onToggle: (name: string) => void;
}

export default function EquipmentSelector({
  options,
  selected,
  onToggle,
}: EquipmentSelectorProps) {
  return (
    <div>
      <h2>Select Equipment</h2>
      <div>
        {options.map((item) => (
          <div key={item.id}>
            <label>
              <input
                type="checkbox"
                checked={selected.includes(item.id)}
                onChange={() => onToggle(item.id)}
              />
              {item.name} ({item.cost})
            </label>
          </div>
        ))}
      </div>
    </div>
  );
}
