// src/components/builder/InventoryManager.tsx
import React from 'react';

// Definiere die Props für den InventoryManager
interface InventoryManagerProps {
  inventory: string[];
  onAdd: (item: string) => void;
  onRemove: (index: number) => void;
}

export default function InventoryManager({
  inventory,
  onAdd,
  onRemove,
}: InventoryManagerProps) {
  const handleAddItem = () => {
    const item = prompt("Enter the inventory item:");
    if (item) {
      onAdd(item);
    }
  };

  return (
    <div>
      <h2>Inventory Manager</h2>
      <button onClick={handleAddItem}>Add Item</button>
      <ul>
        {inventory.map((item, index) => (
          <li key={index}>
            {item}{" "}
            <button onClick={() => onRemove(index)}>Remove</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/app/inventory-manager/inventory-manager.component.ts
// src/app/inventory-manager/inventory-manager.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-inventory-manager',
  templateUrl: './inventory-manager.component.html',
  styleUrls: ['./inventory-manager.component.css']
})
export class InventoryManagerComponent {
  @Input() inventory: string[] = [];
  @Output() onAdd = new EventEmitter<string>();
  @Output() onRemove = new EventEmitter<number>();

  handleAddItem() {
    const item = prompt("Enter the inventory item:");
    if (item) {
      this.onAdd.emit(item);
    }
  }

  handleRemoveItem(index: number) {
    this.onRemove.emit(index);
  }
}

<!-- src/app/inventory-manager/inventory-manager.component.html -->
<div>
    <h2>Inventory Manager</h2>
    <button (click)="handleAddItem()">Add Item</button>
    <ul>
      <li *ngFor="let item of inventory; let i = index">
        {{ item }} <button (click)="handleRemoveItem(i)">Remove</button>
      </li>
    </ul>
  </div>
