// src/components/builder/SpeciesSelector.tsx
import React from 'react';

interface SpeciesSelectorProps {
  speciesList: { id: string; name: string; description: string; lineages: { id: string; name: string; description: string }[] }[];
  selected: string;
  onSelect: React.Dispatch<React.SetStateAction<string>>;
}

export default function SpeciesSelector({
  speciesList,
  selected,
  onSelect,
}: SpeciesSelectorProps) {
  return (
    <div>
      <h2>Select a Species</h2>
      <select value={selected} onChange={(e) => onSelect(e.target.value)}>
        <option value="">Select a Species</option>
        {speciesList.map((species) => (
          <option key={species.id} value={species.id}>
            {species.name}
          </option>
        ))}
      </select>
    </div>
  );
}

// src/app/species-selector/species-selector.component.ts
// src/app/species-selector/species-selector.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-species-selector',
  templateUrl: './species-selector.component.html',
  styleUrls: ['./species-selector.component.css']
})
export class SpeciesSelectorComponent {
  @Input() speciesList: { id: string; name: string; description: string; lineages: { id: string; name: string; description: string }[] }[] = [];
  @Input() selected: string = '';
  @Output() onSelect = new EventEmitter<string>();

  handleSelectionChange(value: string) {
    this.onSelect.emit(value);
  }
}

<!-- src/app/species-selector/species-selector.component.html -->
<div>
    <h2>Select a Species</h2>
    <select [(ngModel)]="selected" (change)="handleSelectionChange(selected)">
      <option value="">Select a Species</option>
      <option *ngFor="let species of speciesList" [value]="species.id">
        {{ species.name }}
      </option>
    </select>
  </div>
